### ISSUE TITLE
Food Items need sprites

### ISSUE THREAD

**Issue by CalebRoenigk** [cd-projekt-deep-red/herding-cats-unity#7]
Food items need sprites, these are in the game repo and have a full half and empty sprite. These states will change based on how much food is left in a can. I figure after the can is empty it will flip up and eventually fade away.

**Comment by ericljiang** [comment]
Fixed in https://github.com/cd-projekt-deep-red/herding-cats-unity/commit/5a5aada4a57155f5c7cc2ec95eeee54f548836b1

**Comment by ericljiang** [comment]
New issue for food cans sticking around https://github.com/cd-projekt-deep-red/herding-cats-unity/issues/16
